"""Plot aggregated results from .npz files generated by run_grid.py."""

import argparse
import glob
import os
from collections import defaultdict

import matplotlib.pyplot as plt
import numpy as np


def smooth(x, window=20):
    if len(x) < window:
        return x
    kernel = np.ones(window) / window
    return np.convolve(x, kernel, mode="valid")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--res-dir", default="results", help="Directory containing .npz files")
    ap.add_argument("--out-dir", default="results", help="Directory to save plots")
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    npz_files = glob.glob(os.path.join(args.res_dir, "*.npz"))
    if not npz_files:
        print(f"No .npz files found in {args.res_dir}")
        return

    # Structure: data[env][mixer][exploration][similarity] = list of returns arrays
    data = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list))))

    for path in npz_files:
        try:
            d = np.load(path, allow_pickle=True)
            env = str(d["cfg_env"])
            mixer = str(d["cfg_mixer"])
            expl = str(d["cfg_exploration"])
            sim = str(d["cfg_similarity"])
            returns = d["returns"]
            
            data[env][mixer][expl][sim].append(returns)
        except Exception as e:
            print(f"Failed to load {path}: {e}")

    for env, mixers in data.items():
        for mixer, expls in mixers.items():
            fig, ax = plt.subplots(figsize=(8, 5))
            
            for expl, sims in expls.items():
                for sim, returns_list in sims.items():
                    if not returns_list:
                        continue
                        
                    min_len = min(len(r) for r in returns_list)
                    if min_len == 0:
                        continue
                        
                    returns_matrix = np.stack([r[:min_len] for r in returns_list])
                    
                    window = max(20, min_len // 50)
                    if min_len < window:
                        window = 1
                        
                    smoothed = np.stack([smooth(r, window) for r in returns_matrix])
                    mean = smoothed.mean(axis=0)
                    std = smoothed.std(axis=0)
                    x = np.arange(len(mean)) + window
                    
                    label = f"{expl}"
                    if expl == "correlated":
                        label += f" ({sim})"
                        
                    p = ax.plot(x, mean, label=f"{label} ({len(returns_list)} seeds)")
                    color = p[0].get_color()
                    ax.fill_between(x, mean - std, mean + std, alpha=0.2, color=color)

            ax.set_xlabel("episode")
            ax.set_ylabel(f"return (smoothed)")
            ax.set_title(f"Env: {env} | Mixer: {mixer}")
            ax.legend()
            ax.grid(alpha=0.3)
            fig.tight_layout()
            out_path = os.path.join(args.out_dir, f"plot_{env}_{mixer}.png")
            fig.savefig(out_path, dpi=120)
            plt.close(fig)
            print(f"Saved plot to {out_path}")


if __name__ == "__main__":
    main()
